### ISSUE TITLE
Not able to add the EMHASS add on

### ISSUE THREAD

**Issue by dutchronnie** [davidusb-geek/emhass-add-on#32]
When i want to add the repository for emhass, i get an error message.

<Integration davidusb-geek/emhass> Repository structure for v0.3.21 is not compliant

I try to add the URL: https://github.com/davidusb-geek/emhass

**Comment by davidusb-geek** [comment]
The correct URL is: https://github.com/davidusb-geek/emhass-add-on

**Comment by dutchronnie** [comment]
Are you sure this is the correct url?

![afbeelding](https://user-images.githubusercontent.com/16868762/212653108-72619714-e12e-4cc0-b69e-ae4c71e88b4d.png)

I am not able to add the repository to Homeassistant

**Comment by davidusb-geek** [comment]
Hi, yes sure it is the correct URL. Very weird behavior. 
That URL has been working fine for one and a half year now and this is the first time that I see this problem. So my guess is that may be there is an issue with your system. Try taking a look at the logs to see the error message when you try to add the URL. Otherwise try to reboot your system.

**Comment by davidusb-geek** [comment]
![image](https://user-images.githubusercontent.com/32926550/212673273-7e6c0e0f-f120-46fd-8079-5eb542e60f08.png)

**Comment by dutchronnie** [comment]
This is very strange, i just tried again, with the same url, and now the repository is added.

It was not 1 try , with the error message, yesterday tried several times, and also this morning.
I have not rebooted the system. 

But it works now, thanks
